export const metadata = {
  title: 'View Detail Blog',
  description: 'Generated by Hoi Dan IT',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
    </>
  )
}
